#!/usr/bin/env sh

[[ "$(acpi 2>&1)" = "" ]] && exit 33;

state=$(acpi | awk -F [',:'] '{print $2}' | sed 's/\ //')
declare -i perc=$(acpi | awk -F [','] '{print $2}' | sed 's/\%//; s/\ //')
time=$(acpi | awk -F [':,'] '{print $4":"$5}' | sed 's/\ //')

if [[ "$state" == 'Discharging' ]]; then
	if [[ $perc -le 5 ]];then
		echo "<span background='red'><b>Low battery</b></span>"
		notify-send -u critical "$bat$perc% Low battery\n$time"
	elif [[ $perc -le 15 ]];then
		color="#FF0000"
		bat='  '
		notify-send -u critical "$bat$perc% Low battery\n$time"
	elif [[ $perc -le 30 ]];then
		color="FFAE00"
		bat='  '
	elif [[ $perc -le 50 ]];then
		color="#FFF600"
		bat='  '
	elif [[ $perc -le 75 ]];then 
		color="#A8FF00"
		bat='  ' 
	elif [[ $perc -le 100 ]]
	then
		color="#A8FF00"
		bat='  '
	fi
elif [[ "$state" == 'Charging' ]];then
	color="#FFFFFF"
	bat='  ' 
elif [[ "$state" == 'Full' ]];then
	echo "<span background='red'>🔋<b>Battery full</b></span>"
	notify-send -u critical "Battery FUll"
fi

echo "<span foreground='$color'>🔋$perc%$bat($time)</span>"
