#!/usr/bin/bash


declare -i bright=$(cat /sys/class/backlight/intel_backlight/brightness)
declare -i maxbright=5200


case $BLOCK_BUTTON in
	1) echo 0 > /sys/class/backlight/intel_backlight/brightness ;;
	4) echo $((bright+10*maxbright/100)) > /sys/class/backlight/intel_backlight/brightness ;;
	5) echo $((bright-10*maxbright/100)) > /sys/class/backlight/intel_backlight/brightness ;;
esac

declare -i actualbright=$(cat /sys/class/backlight/intel_backlight/actual_brightness)

if [[ $actualbright -le $((maxbright/2)) ]]
then icon=🔅
else
	icon=🔆
fi


echo $icon$((actualbright*100/maxbright))%
