#!/usr/bin/env sh

case $BLOCK_BUTTON in
	1) notify-send "Top CPU hogs:" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)"
esac

cpuDBAR () {

	warn=70
	crit=90
	therm=""
	color="#FFFFFF"
	  
	declare -i temp=$(sensors acpitz-acpi-0 | awk -F "['+.']" '/^temp1/ {print $2}')

	if [[ $temp -ge $warn ]];then
		color="#FFFC00"
		therm=""
	elif [[ $temp -ge $crit ]];then
		color="#FF0000"
		therm=""
	fi

	echo "<span color='$color'>$therm $((temp))C°</span>"
}

cpuDBAR
