#!/usr/bin/env sh

if [[ "$(cmus-remote -Q 2>&1)" = "cmus-remote: cmus is not running" ]];then
	playerctl play-pause && kill -9 $(cat $HOME/github/dwm-bar/dwmpid) && kill -9 $(cat ~/.cache/pid/cmus-lyrics)
fi
