#!/bin/zsh

declare -i brightness=$(xbacklight)

if [[ $brightness -le 50 ]]
then icon=🔅
else
	icon=🔆
fi

xbacklight -dec 10 -time 0

# pkill -RTMIN+9 dwmblocks
kill -9 $(cat $HOME/github/dwm-bar/dwmpid)
pkill -RTMIN+9 i3blocks

notify-send "$icon $(xbacklight | awk -F "['.']" '{print $1}')%" -h string:x-canonical-private-synchronous:anything
