#!/bin/zsh

declare -i brightness=$(xbacklight)

if [[ $brightness -le 50 ]]
then icon=🔅
else
	icon=🔆
fi

pkill -RTMIN+9 i3blocks
notify-send "$icon $brightness%" -h string:x-canonical-private-synchronous:anything
xbacklight -dec 10
