#!/bin/zsh

declare -i brightness=$(xbacklight)

if [[ $brightness -le 50 ]]
then icon=🔅
else
	icon=🔆
fi

xbacklight -inc 10 -time 0
pkill -RTMIN+9 i3blocks
notify-send "$icon $brightness%" -h string:x-canonical-private-synchronous:anything
