#!/usr/bin/env sh

alias vim="nvim" \
	ran="ranger" \
	py="python3" \
	py2="python2" \
	mixer="alsamixer -g" \
	mutt="neomutt" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	yt="youtube-dl --add-metadata -i -o '%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	upc="sudo pacman -Syu" \
	SS="sudo systemctl" \
	PS="sudo pacman -S" \
	PQ="sudo pacman -Q" \
	PR="sudo pacman -Rnu" \
	cpu="ps axch -o cmd:15,%cpu --sort=-%cpu | head" \
	mem="ps axch -o cmd:15,%mem --sort=-%mem | head" \
	gs="cd $HOME/.local/bin" \
	gi="cd $HOME/.config" \
	gr="cd $HOME/github" \
	gR="cd $HOME/SSD/College/PhD/ref" \
	gp="cd $HOME/SSD/College/PhD" \
	gP="cd $HOME/external/personal" \
	gm="cd $HOME/SSD/College/M.Sc" \
	gM="cd $HOME/data/Music" \
	gh="cd $HOME/" \
	gt="cd $HOME/external/personal/torrents" \
	gd="cd $HOME/Downloads" \
	gk="cd $HOME/external/personal/piano" \
	gl="cd $HOME/SSD/projects/OT" \
	efa="nvim $HOME/.config/aliasrc" \
	efz="nvim $HOME/.zshrc" \
	efn="nvim $HOME/.config/nvim/init.vim" \
	TR="tremc" \
	TA="transadd"\
	tl="transmission-remote -l" \
	env="source $HOME/.venv/p39/bin/activate" \
	tf="source $HOME/.venv/p38/bin/activate" \
	list="nmcli device wifi list" \
	con="nmcli device wifi connect -ask" \
	P="aplaymidi -p 24" \
	R="arecordmidi -p 24"


command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

cw() { feh --bg-fill --randomize -r $HOME/Pictures ;}
sc() { du -a ~/.config/* | awk '{print $2}' | fzf | xargs -r $EDITOR ;}
ss() { du -a ~/.local/bin/* | awk '{print $2}' | fzf | xargs -r $EDITOR ;}
vf() { fzf | xargs -r -I % $EDITOR % ;}
